CREATE DATABASE SALES;
USE SALES;
-- CREATE SCHEMA COHORT_ANALYSIS;
-- rename table `retail cohort` to retail;

SELECT * FROM RETAIL LIMIT 10;
SELECT COUNT(*) FROM RETAIL; -- 22,190 Records;
select count(*) from retail where customerid is null; -- 0

select max(InvoiceDate) from retail;

-- Cohort Analysis on Customer Level
with cte1 as(
SELECT
InvoiceNo, CUSTOMERID,
str_to_date(INVOICEDATE, "%d/%m/%Y %H:%i") AS INVOICEDATE,
ABS(ROUND(QUANTITY*UNITPRICE, 2)) AS REVENUE
FROM RETAIL
WHERE CUSTOMERID IS NOT NULL and CUSTOMERID <> ''),
cte2 as(
SELECT InvoiceNo, CUSTOMERID, INVOICEDATE,
DATE_FORMAT(INVOICEDATE, '%Y-%m-01') AS PURCHASE_MONTH,
DATE_FORMAT(MIN(INVOICEDATE) OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE), '%Y-%m-01') AS FIRST_PURCHASE_MONTH,
REVENUE
FROM CTE1),
CTE3 AS
(SELECT CUSTOMERID, FIRST_PURCHASE_MONTH,
CONCAT('Month_' , 
	period_diff(
		Extract(Year_MONTH from PURCHASE_MONTH),
		Extract(Year_Month from FIRST_PURCHASE_MONTH)
			)
		) AS COHORT_MONTH
FROM CTE2)
SELECT FIRST_PURCHASE_MONTH as Cohort,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_0',CUSTOMERID,null)) as Month_0,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_1',CUSTOMERID,null)) as Month_1,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_2',CUSTOMERID,null)) as Month_2,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_3',CUSTOMERID,null)) as Month_3,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_4',CUSTOMERID,null)) as Month_4,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_5',CUSTOMERID,null)) as Month_5,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_6',CUSTOMERID,null)) as Month_6,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_7',CUSTOMERID,null)) as Month_7,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_8',CUSTOMERID,null)) as Month_8,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_9',CUSTOMERID,null)) as Month_9,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_10',CUSTOMERID,null)) as Month_10,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_11',CUSTOMERID,null)) as Month_11,
COUNT(DISTINCT IF(COHORT_MONTH= 'Month_12',CUSTOMERID,null)) as Month_12
FROM CTE3
GROUP BY FIRST_PURCHASE_MONTH
ORDER BY FIRST_PURCHASE_MONTH;
